timeout: 5

/zinnia
	kaslr: no
	protocol: limine
	path: boot():/zinnia
	module_path: boot():/initramfs.tar
	cmdline: console=com1

/zinnia (Shell)
	kaslr: no
	protocol: limine
	path: boot():/zinnia
	module_path: boot():/initramfs.tar
	cmdline: rd.init=/usr/bin/sh

/Debugging
	//zinnia (fastfetch)
		kaslr: no
		protocol: limine
		path: boot():/zinnia
		module_path: boot():/initramfs.tar
		cmdline: rd.init=/usr/bin/fastfetch
