#! /bin/sh

name=extra-cmake-modules
version=6.14.0
git_url="https://github.com/KDE/extra-cmake-modules.git"
commit=a5f0366eb92baa2a31b24e65f754fe4bc48ca28e
# imagedeps="git"
# allow_network=yes
# shallow=no

prepare() {
	sed -i '/"lib64"/s/64//' ${source_dir}/kde-modules/KDEInstallDirsCommon.cmake

	sed -e '/PACKAGE_INIT/i set(SAVE_PACKAGE_PREFIX_DIR "${PACKAGE_PREFIX_DIR}")' \
    	-e '/^include/a set(PACKAGE_PREFIX_DIR "${SAVE_PACKAGE_PREFIX_DIR}")' \
    	-i ${source_dir}/ECMConfig.cmake.in
}
