#! /bin/sh

name=menix
version=0.1.0
git_url=https://github.com/menix-os/menix.git
commit=a3608f7354ec2f4c04671339481d28d11f6d2978
imagedeps="rustup git"
allow_network=yes
shallow=no

prepare() {
        RUSTUP_HOME="${build_dir}/.rustup" \
    rustup toolchain install nightly --component rust-src

        RUSTUP_HOME="${build_dir}/.rustup" \
    rustup default nightly

    git submodule update --init --recursive
}
