#! /bin/sh

name=menix
version=0.1.0
git_url=https://github.com/menix-os/menix.git
commit=a8608f6182a209d5513182af21603e053ac160cc
imagedeps="rustup git"
allow_network=yes
shallow=no

prepare() {
        RUSTUP_HOME="${JINX_CACHE_DIR}/.rustup" \
    rustup toolchain install nightly --component rust-src

        RUSTUP_HOME="${JINX_CACHE_DIR}/.rustup" \
    rustup default nightly

    git submodule update --init --recursive
}
