#! /bin/sh

name=menix
version=0.0
revision=1
git_url=https://github.com/menix-os/menix.git
branch=main
imagedeps="rustup git"
allow_network=yes

prepare() {
        RUSTUP_HOME="${JINX_CACHE_DIR}/.rustup" \
    rustup toolchain install nightly --component rust-src

        RUSTUP_HOME="${JINX_CACHE_DIR}/.rustup" \
    rustup default nightly

    git submodule update --init --recursive
}
