#! /bin/sh

name=zinnia
version=0.2.0
git_url=https://github.com/zinnia-os/zinnia.git
commit=b40bdcc99146321056369e9c0ea15baa60d4be8e
imagedeps="git"
allow_network=yes
shallow=no

prepare() {
    git submodule update --init --recursive
}
