#! /bin/sh

name=zinnia
version=0.1.0
git_url=https://github.com/zinnia-os/zinnia.git
commit=21f792d336857c70ae0f73faf262bb23e74a3e62
imagedeps="git"
allow_network=yes
shallow=no

prepare() {
    git submodule update --init --recursive
}
