#! /bin/sh

name=drm-test
version=0.1
revision=1
hostdeps="gcc pkg-config"
deps="core-libs libdrm"

build() {
    ${OS_TRIPLET}-gcc -I${sysroot_dir}/usr/include/libdrm -ldrm -o drm-test "${base_dir}/extras/drm-test/main.c"
}

package() {
    mkdir -p ${dest_dir}/usr/bin
    cp drm-test ${dest_dir}/usr/bin/drm-test
}
