#! /bin/sh

name=ecm
version=6.14.0
revision=1
from_source=extra-cmake-modules
hostdeps="gcc pkg-config cmake"
deps="qtbase6"

configure() {
	cmake_configure \
        -DBUILD_WITH_QT6=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
