#! /bin/sh

name=frigg
version=d79bfd49fcd1458dbe8a5f3c10880800b108cc14
revision=1
git_url="https://github.com/managarm/frigg.git"
commit=${version}
imagedeps="meson ninja-build"
hostdeps="pkg-config"

configure() {
    meson_configure \
        --includedir=share/frigg/include \
        -Dbuild_tests=disabled
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
