#! /bin/sh

name=frigg
version=6355f7677fa39156aeb77603d246d977531e28ee
revision=1
git_url="https://github.com/managarm/frigg.git"
commit=${version}
imagedeps="meson ninja-build"
hostdeps="pkg-config"

configure() {
    meson_configure \
        --includedir=share/frigg/include \
        -Dbuild_tests=disabled
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
