#! /bin/sh

name=frigg
version=a00f2df620213e616ed370bde537e9d1d69e4301
revision=1
git_url="https://github.com/managarm/frigg.git"
commit=${version}
imagedeps="meson ninja-build"
hostdeps="pkg-config"

configure() {
    meson_configure \
        --includedir=share/frigg/include \
        -Dbuild_tests=disabled
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
