#! /bin/sh

name=gcc
from_source=gcc
hostdeps="gcc pkg-config"
deps="core-libs binutils zlib gmp mpfr mpc"
imagedeps="build-essential"

prepare() {
    for i in "${base_dir}"/patches/gcc-host/*; do
        patch -p1 < "$i"
    done

    autotools_recursive_regen
}

configure() {
    autotools_configure \
        CFLAGS_FOR_BUILD="$HOST_CFLAGS" \
        CPPFLAGS_FOR_BUILD="$HOST_CPPFLAGS" \
        CXXFLAGS_FOR_BUILD="$HOST_CXXFLAGS" \
        LDFLAGS_FOR_BUILD="$HOST_LDFLAGS" \
        CFLAGS_FOR_TARGET="$TARGET_CFLAGS" \
        CPPFLAGS_FOR_TARGET="$TARGET_CPPFLAGS" \
        CXXFLAGS_FOR_TARGET="$TARGET_CXXFLAGS" \
        LDFLAGS_FOR_TARGET="$TARGET_LDFLAGS" \
        --target=${OS_TRIPLET} \
        --with-sysroot=/ \
        --with-build-sysroot=${sysroot_dir} \
        --with-linker-hash-style=gnu \
        --enable-linker-build-id \
        --enable-languages=c,c++,lto \
        --enable-default-pie \
        --enable-default-ssp \
        --enable-initfini-array \
        --disable-multilib \
        --with-system-zlib \
        --enable-host-shared
}

build() {
    make -j${parallelism} all-gcc
}

package() {
    DESTDIR="${dest_dir}" make install-gcc

    ln -s gcc "${dest_dir}${prefix}"/bin/cc

    # Remove static libraries
    rm -rf "${dest_dir}${prefix}"/lib/*.a

    post_package_strip
}
