#! /bin/sh

name=libcap
version=2.72
revision=1
tarball_url="https://mirrors.edge.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-${version}.tar.xz"
tarball_blake2b="2c854fd9a714ab1daae3831829b4b7a890a0894953ba88ae1e190274e7fc635275ce4bf2c668b390ba8196248cb1f953fafb3a9af3907e688c1ab40774f7c6e0"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs"

build() {
    cp -rp "${source_dir}"/. ./

    make -j${parallelism} \
        prefix="${prefix}" \
        lib=lib \
        sbindir=bin \
        PAM_CAP=no \
        DYNAMIC=yes \
        GOLANG=no \
        CROSS_COMPILE=${OS_TRIPLET}- \
        BUILD_CC=gcc \
        BUILD_ld=ld
}

package() {
    make install \
        prefix="${prefix}" \
        lib=lib \
        sbindir=bin \
        DESTDIR="${dest_dir}" \
        RAISE_SETFCAP=no \
        CROSS_COMPILE=${OS_TRIPLET}- \
        BUILD_CC=gcc \
        BUILD_ld=ld

    # Remove static libraries
    rm -rf "${dest_dir}${prefix}"/lib/*.a

    post_package_strip
}
