#! /bin/sh

name=libudev
version=259
revision=1
git_url="https://github.com/marv7000/libudev-freestanding.git"
commit="3a7170ebb73c201d69e6224c279d3885616c7e15"
hostdeps="gcc pkg-config"
deps="core-libs libevdev"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip

    mkdir -p "${dest_dir}/etc/udev/"
    cp -rp "${base_dir}/extras/libudev/." "${dest_dir}/etc/udev/"
}
