#! /bin/sh

name=limine
version=10.2.0
revision=1
tarball_url="https://codeberg.org/Limine/Limine/releases/download/v${version}/limine-${version}.tar.gz"
tarball_blake2b="22e11bffe35bf5bb8a884f1f53af55eca1b1978c1584c365707f8cfd9065cff048aacfac4eef3d46e78cd7f286870c2d8ba8342dc7fd1f84bdffffb34d1949bc"
imagedeps="clang build-essential lld llvm mtools nasm"
hostdeps="gcc binutils autoconf automake"
deps="core-libs"
source_hostdeps="automake autoconf"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-all
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
