#! /bin/sh

name=limine
version=9.2.2
revision=1
tarball_url="https://github.com/limine-bootloader/limine/releases/download/v${version}/limine-${version}.tar.gz"
tarball_blake2b="f3085f67d6ba41eef2e5f34de671a307e6034339d16ce5f0e09b08c5d3a32e332a0cdc55fd78872d92e60797d5a03905c06aa4094930b96be8fc7ca504acee84"
imagedeps="clang build-essential lld llvm mtools nasm"
hostdeps="gcc autoconf automake"
deps="core-libs"
source_hostdeps="automake autoconf"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        TOOLCHAIN_FOR_TARGET=llvm \
        --enable-all
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

        strip_command=strip \
    post_package_strip
}
