#! /bin/sh

name=llvm
repology_id="llvm"
from_source=llvm
revision=1
imagedeps="build-essential"
hostdeps="gcc pkg-config cmake"
deps="core-libs ncurses zlib zstd libffi"

configure() {
        cmake_source_dir="${source_dir}/llvm" \
    cmake_configure \
        -UBUILD_SHARED_LIBS \
        -UENABLE_STATIC \
        -DLLVM_LINK_LLVM_DYLIB=ON \
        -DLLVM_ENABLE_FFI=ON \
        -DLLVM_ENABLE_EH=ON \
        -DLLVM_ENABLE_RTTI=ON \
        -DLLVM_DEFAULT_TARGET_TRIPLE=${OS_TRIPLET} \
        -DLLVM_HOST_TRIPLE=${OS_TRIPLET} \
        -Wno-dev
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    rm -rf "${dest_dir}${prefix}"/lib/*.a
    # rm -rf "${dest_dir}${prefix}"/bin

    post_package_strip
}
