#! /bin/sh

name=menix-utils
version=0.1.0
revision=1
git_url="https://github.com/menix-os/menix-utils.git"
commit="9e0a28df0f21d50d8bee1503140cc01f0c72b9d6"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
