#! /bin/sh

name=menix-debug
from_source=menix
imagedeps="build-essential rustup"
allow_network=yes
hostdeps="llvm"
builddeps="mlibc-headers"
allow_source_writes="yes"

build() {
    cargo_build \
        --target="${source_dir}/toolchain/${ARCH}-kernel.json" \
        --config="${source_dir}/.cargo/config.toml"
}

package() {
    mkdir -p "${dest_dir}${prefix}/share/menix-debug/"
    mkdir -p "${dest_dir}${prefix}/share/menix-debug/modules"

    cp "${ARCH}-kernel/debug/menix.kso" "${dest_dir}${prefix}/share/menix-debug/menix"
    install -m644 "${ARCH}-kernel/debug/"*.kso "${dest_dir}${prefix}/share/menix-debug/modules"
    rm "${dest_dir}${prefix}/share/menix-debug/modules/menix.kso"
}
