#! /bin/sh

name=menix
from_source=menix
revision=1
imagedeps="build-essential rustup"
allow_network=yes
hostdeps="llvm"
builddeps="mlibc-headers"
skip_pkg_check=yes

MENIX_ARCH="${JINX_ARCH}"
case "${MENIX_ARCH}" in
    "riscv64") MENIX_ARCH="riscv64gc" ;;
esac

build() {
        TARGET_CC="clang" \
    cargo_build \
        --release \
        --target="toolchain/${MENIX_ARCH}-kernel.json"
}

package() {
    mkdir -p "${dest_dir}${prefix}/share/menix/"
    mkdir -p "${dest_dir}${prefix}/share/menix/modules"

    cp "target/${MENIX_ARCH}-kernel/release/menix.kso" "${dest_dir}${prefix}/share/menix/menix"
    post_package_strip "${dest_dir}${prefix}/share/menix/menix" -R .rustc
    install -m644 "target/${MENIX_ARCH}-kernel/release/"*.kso "${dest_dir}${prefix}/share/menix/modules"
    rm "${dest_dir}${prefix}/share/menix/modules/menix.kso"
}
