#! /bin/sh

name=menix-utils
from_source=menix
revision=1
hostdeps="gcc"
skip_pkg_check=yes

configure() {
    meson_configure \
        -Dutils=true \
        -Dkernel=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}
