#! /bin/sh

name=menix
from_source=menix
revision=1
imagedeps="build-essential meson ninja-build"
hostdeps="binutils gcc pkg-config"
deps="core-libs"
skip_pkg_check=yes

configure() {
    meson_configure_noflags \
        --buildtype=debug
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
