#! /bin/sh

name=menix-headers
from_source=menix
revision=1
imagedeps="build-essential meson ninja-build"
hostdeps="binutils gcc pkg-config"
skip_pkg_check=yes

configure() {
    meson_configure_noflags \
        -Dheaders_only=true
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}
