#! /bin/sh

name=menix
from_source=menix
revision=1
imagedeps="build-essential rustup"
allow_network=yes
hostdeps="llvm"
builddeps="mlibc-headers"
skip_pkg_check=yes

build() {
    cargo_build \
        --release \
        --target="toolchain/${JINX_ARCH}-kernel.json"
}

package() {
    mkdir -p "${dest_dir}${prefix}/share/menix/"
    mkdir -p "${dest_dir}${prefix}/share/menix/modules"

    cp "${JINX_ARCH}-kernel/release/menix.kso" "${dest_dir}${prefix}/share/menix/menix"
    strip "${dest_dir}${prefix}/share/menix/menix" -R .rustc
    install -m644 "${JINX_ARCH}-kernel/release/"*.kso "${dest_dir}${prefix}/share/menix/modules"
    rm "${dest_dir}${prefix}/share/menix/modules/menix.kso"
}
