#! /bin/sh

name=menix-debug
from_source=menix
revision=1
imagedeps="build-essential rustup"
allow_network=yes
hostdeps="llvm"
builddeps="mlibc-headers"
skip_pkg_check=yes

build() {
    cargo_build \
        --target="toolchain/${JINX_ARCH}-kernel.json"
}

package() {
    mkdir -p "${dest_dir}${prefix}/share/menix-debug/"
    mkdir -p "${dest_dir}${prefix}/share/menix-debug/modules"

    cp "target/${JINX_ARCH}-kernel/debug/menix.kso" "${dest_dir}${prefix}/share/menix-debug/menix"
    install -m644 "target/${JINX_ARCH}-kernel/debug/"*.kso "${dest_dir}${prefix}/share/menix-debug/modules"
    rm "${dest_dir}${prefix}/share/menix-debug/modules/menix.kso"
}
