#! /bin/sh

name=menix-headers
from_source=menix
revision=1
imagedeps="build-essential meson ninja-build"
hostdeps="gcc"
skip_pkg_check=yes

configure() {
    meson_configure \
        -Dheaders_only=true
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install
}
