#! /bin/sh

name=menix-debug
from_source=menix
imagedeps="build-essential rustup"
allow_network=yes
hostdeps="llvm"
builddeps="mlibc-headers"
allow_source_writes="yes"

build() {
    cargo_build \
        --target="${source_dir}/toolchain/${ARCH}-kernel.json" \
        -Zbuild-std=core,alloc \
        -Zbuild-std-features=compiler-builtins-mem
}

package() {
    mkdir -p "${dest_dir}${prefix}/share/menix/"
    install -m644 ${ARCH}-kernel/debug/menix.kso "${dest_dir}${prefix}/share/menix/menix-debug"
}
