#! /bin/sh

name=mesa
version=25.0.5
revision=1
tarball_url="https://archive.mesa3d.org/mesa-${version}.tar.xz"
tarball_blake2b="f17f8c2a733fd3c37f346b9304241dc1d13e01df9c8c723b73b10279dd3c2ebed062ec1f15cdbc8b9936bae840a087b23ac38cae7d8982228d582d468ab8c9c9"
imagedeps="python3-mako python3-yaml glslang-tools pkg-config"
hostdeps="gcc pkg-config"
deps="core-libs libdrm libexpat libglvnd libx11 libxcb libxext libxfixes libxrandr libxshmfence libxxf86vm llvm xcb-util-keysyms zlib zstd"

configure() {
# -Dgallium-drivers=r300,r600,nouveau,virgl,svga,i915,crocus,zink,softpipe,llvmpipe \
# -Dvulkan-drivers=amd,swrast,virtio \
#         -Dvulkan-layers=device-select,intel-nullhw,overlay \
    meson_configure \
        -Db_ndebug=true \
        -Dbuild-tests=false \
        -Dshared-glapi=enabled \
        -Dexpat=enabled \
        -Dgbm=enabled \
        -Dgles1=enabled \
        -Dgles2=enabled \
        -Dglvnd=enabled \
        -Degl=enabled \
        -Dllvm=enabled \
        -Dzstd=enabled \
        -Dosmesa=false \
        -Dvideo-codecs=all_free \
        -Dvulkan-drivers='' \
        -Dgallium-drivers=softpipe,llvmpipe \
        -Dgallium-extra-hud=true \
        -Dgallium-rusticl=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
