#! /bin/sh

name=qtbase6
version=6.8.1
revision=2
git_url="https://code.qt.io/qt/qtbase.git"
commit=0db4321f2f13c6870283f3fcc0f1a462fd7cf663
hostdeps="gcc pkg-config cmake qt6"
deps="core-libs pcre2 sqlite glib2 systemd icu mesa zlib zstd pcre2 double-conversion libxkbcommon libinput libevdev mtdev freetype2 fontconfig libpng harfbuzz libx11 libjpeg-turbo libsm libice libdrm libxcb xcb-util-image xcb-util-keysyms xcb-util-wm xcb-util-renderutil xcb-util-cursor openssl wayland wayland-protocols libxcursor libxinerama libxrender libxi brotli dbus at-spi2-core"

configure() {
    cmake_configure \
        -DQT_HOST_PATH="${build_dir}/host-pkgs/qt6/usr/local" \
        -DINSTALL_BINDIR=bin \
        -DINSTALL_INCLUDEDIR=include/qt6 \
        -DINSTALL_LIBDIR=lib \
        -DINSTALL_ARCHDATADIR=lib/qt6 \
        -DINSTALL_PLUGINSDIR=lib/qt6/plugins \
        -DINSTALL_LIBEXECDIR=lib/qt6/libexec \
        -DINSTALL_QMLDIR=lib/qt6/qml \
        -DINSTALL_DATADIR=share/qt6 \
        -DINSTALL_DOCDIR=share/qt6-doc \
        -DINSTALL_TRANSLATIONSDIR=share/qt6/translations \
        -DINSTALL_SYSCONFDIR=/etc/xdg \
        -DINSTALL_MKSPECSDIR=lib/qt6/mkspecs \
        -DINSTALL_EXAMPLESDIR=share/qt6/examples \
        -DBUILD_SHARED_LIBS=ON \
        -DQT_BUILD_EXAMPLES=OFF \
        -DQT_BUILD_TESTS=OFF \
        -DFEATURE_concurrent=ON \
        -DFEATURE_dbus=ON \
        -DFEATURE_gui=ON \
        -DFEATURE_network=ON \
        -DFEATURE_printsupport=ON \
        -DFEATURE_sql=ON \
        -DFEATURE_testlib=ON \
        -DFEATURE_widgets=ON \
        -DFEATURE_libudev=ON \
        -DFEATURE_icu=ON \
        -DFEATURE_glib=ON \
        -DFEATURE_pcre2=ON \
        -DFEATURE_xml=ON \
        -DFEATURE_harfbuzz=ON \
        -DFEATURE_xkbcommon=ON \
        -DFEATURE_xkbcommon_x11=ON \
        -DFEATURE_libinput=ON \
        -DFEATURE_evdev=ON \
        -DFEATURE_mtdev=ON \
        -DFEATURE_egl=ON \
        -DFEATURE_opengl=ON \
        -DFEATURE_accessibility=ON \
        -DFEATURE_xlib=ON \
        -DFEATURE_xcb=ON \
        -DFEATURE_xcb_xlib=ON \
        -DFEATURE_eglfs_gbm=ON \
        -DFEATURE_eglfs_egldevice=ON \
        -DFEATURE_gtk3=OFF \
        -DFEATURE_system_sqlite=ON \
        -DFEATURE_cups=OFF \
        -DFEATURE_ssl=ON \
		-Wno-dev
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
