#! /bin/sh

name=qtdeclarative6
version=6.8.1
revision=1
git_url="https://code.qt.io/qt/qtdeclarative.git"
commit=b34fca34941ecdbf99819bbf58b45332ac9e6fa7
# Needed to invoke host tooling
imagedeps="build-essential libwayland-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev libgl-dev libxcb-xinerama0-dev libxcb-screensaver0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-record0-dev libxcb-randr0-dev libxcb-present-dev libxcb-damage0-dev libxcb-cursor-dev libxcb-dri3-dev libxcb-dri2-0-dev libxcb-glx0-dev libxcb-xinput-dev libxcb-res0-dev libxcb-xf86dri0-dev libxcb-dpms0-dev libxcb-ewmh-dev libxcb-util0-dev libxcb-keysyms1-dev libxcb-icccm4-dev pkg-config"
hostdeps="gcc pkg-config cmake qt6"
deps="core-libs qtbase6 qtimageformats6 qtlanguageserver6 qtshadertools6 qtsvg6 libxkbcommon mesa"

configure() {
    cmake_configure \
        -DQT_HOST_PATH="${build_dir}/host-pkgs/qt6/usr/local" \
		-Wno-dev
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
