#! /bin/sh

name=qtlanguageserver6
version=6.8.1
revision=1
git_url="https://code.qt.io/qt/qtlanguageserver.git"
commit=94f2eea60bcea5221e9a31211fbe4e99009d2558
hostdeps="gcc pkg-config cmake qt6"
deps="core-libs qtbase6"

configure() {
    cmake_configure \
        -DQT_HOST_PATH=${build_dir}/host-pkgs/qt6/usr \
		-Wno-dev
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
