#! /bin/sh

name=qtsvg6
version=6.8.1
revision=1
git_url="https://code.qt.io/qt/qtsvg.git"
commit=ab734c4e83b04acd62d7ba7d7db4d5d83ca58fa9
hostdeps="gcc pkg-config cmake qt6"
deps="core-libs qtbase6 zlib"

configure() {
    cmake_configure \
        -DQT_HOST_PATH="${build_dir}/host-pkgs/qt6/usr/local" \
		-Wno-dev
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
