#! /bin/sh

name=test
version=0.1
revision=1
hostdeps="gcc pkg-config"
deps="core-libs"

build() {
    echo '
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <sys/wait.h>
#include <sched.h>
#include <sys/utsname.h>

int main() {
    printf("Hello, world!\n");

    int forked = fork();
    if (forked) {
        printf("I am the parent for %i\n", forked);
    } else {
        execl("/usr/bin/fastfetch", "/usr/bin/fastfetch", NULL);
    }

    int error;
    waitpid(forked, &error, 0);
    printf("Child exited with code %i\n", WEXITSTATUS(error));
    return 0;
}
' > main.c

    ${OS_TRIPLET}-gcc -o test main.c
}

package() {
    mkdir -p ${dest_dir}/usr/bin
    cp test ${dest_dir}/usr/bin/test
}
