#! /bin/sh

name=util-linux
version=2.40
revision=1
tarball_url="https://www.kernel.org/pub/linux/utils/util-linux/v${version}/util-linux-${version}.tar.xz"
tarball_blake2b="7530b391be06c1213c562b8b1dc427ca3899523564650a08b7dfafd4cdd863021c02eed897dfc3a7ad9fcc9a6ee034abd1f2593b56b2aee2b415305727d76469"
source_hostdeps="gcc pkg-config autoconf automake libtool"
source_imagedeps="gtk-doc-tools"
hostdeps="gcc pkg-config"
deps="core-libs ncurses file zlib"

prepare() {
    # Modified configure.ac, must autoreconf
    autoreconf -fvi
}

configure() {
    # partx and losetup give linker errors
    # Same for mount
    autotools_configure \
        ADJTIME_PATH=/var/lib/hwclock/adjtime \
        --disable-makeinstall-chown \
        --disable-chfn-chsh \
        --disable-login \
        --disable-nologin \
        --disable-sulogin \
        --disable-su \
        --disable-setpriv \
        --disable-runuser \
        --disable-lscpu \
        --disable-pylibmount \
        --without-python \
        --disable-liblastlog2 \
        --without-btrfs \
        --disable-agetty \
        --disable-ipcrm \
        --disable-ipcs
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
