[package]
name = "mlibc-headers"
version = "latest"
archs = ["x86_64"]
shared_source = "mlibc"

[dependencies]
host = ["meson", "ninja"]

[configure]
script = """
meson_configure -Dheaders_only=true
"""

[build]
script = """
ninja -j${THREADS}
"""

[install]
script = """
ninja install
"""
