[package]
name = "host-binutils"
version = "latest"
archs = ["x86_64"]
host = true

[[sources]]
repo = "https://sourceware.org/git/binutils-gdb.git"
branch = "master"
patches = ["menix.patch"]

[dependencies]
host = ["make", "automake", "gcc", "ld", "as", "pkg-config"]

[configure]
script = """
${SOURCE_DIR}/configure \
	--target=${OS_TRIPLET} \
	--disable-werror \
	--with-pic \
	--with-sysroot="${SYSROOT_DIR}" \
	--prefix="${PREFIX_HOST}"
"""

[build]
script = """
make -j${THREADS}
"""

[install]
script = """
make install
"""
