[package]
name = "host-autoconf"
version = "2.72"
archs = []
host = true

[[sources]]
url = "https://ftp.gnu.org/gnu/autoconf/autoconf-2.72.tar.xz"
path = "autoconf-2.72.tar.xz"
patches = ["menix.patch"]

[dependencies]
host = ["autoconf"]

[configure]
script = """
${SOURCE_DIR}/configure --host="${OS_TRIPLET}" --prefix="${PREFIX_HOST}"
"""

[build]
script = """
make -j${THREADS}
"""

[install]
script = """
make install
"""
