[package]
name = "initrd"
version = "latest"
archs = ["x86_64"]
shared_source = "kernel"
shared_build = "kernel"

[install]
script = """
rm -rf ${BUILD_DIR}/initrd_build/
mkdir -p ${BUILD_DIR}/initrd_build/boot/
cp -r ${INSTALL_DIR}/bin ${BUILD_DIR}/initrd_build/bin
cp -r ${INSTALL_DIR}/etc ${BUILD_DIR}/initrd_build/etc
cp -r ${INSTALL_DIR}/usr ${BUILD_DIR}/initrd_build/usr
cp -r ${BUILD_DIR}/bin/mod ${BUILD_DIR}/initrd_build/boot/modules
cd ${BUILD_DIR}/initrd_build

tar -cvf ${BUILD_DIR}/initrd .

mkdir -p ${INSTALL_DIR}/boot/
cp ${BUILD_DIR}/initrd ${INSTALL_DIR}/boot/
"""
