#! /bin/sh

name=ecm
version=6.14.0
revision=1
from_source=extra-cmake-modules
imagedeps="build-essential"
# imagedeps="build-essential libwayland-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev libgl-dev libxcb-xinerama0-dev libxcb-screensaver0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-record0-dev libxcb-randr0-dev libxcb-present-dev libxcb-damage0-dev libxcb-cursor-dev libxcb-dri3-dev libxcb-dri2-0-dev libxcb-glx0-dev libxcb-xinput-dev libxcb-res0-dev libxcb-xf86dri0-dev libxcb-dpms0-dev libxcb-ewmh-dev libxcb-util0-dev libxcb-keysyms1-dev libxcb-icccm4-dev pkg-config"
hostdeps="cmake"
# deps="core-libs"

configure() {
	cmake  \
        "${source_dir}/" \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DBUILD_WITH_QT6=ON \
        -GNinja \
        -Wno-dev
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

        strip_command=strip \
    post_package_strip
}
