#! /bin/sh

name=limine
from_source=limine
revision=1
imagedeps="clang build-essential lld llvm mtools nasm"

configure() {
        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        LDFLAGS="$HOST_LDFLAGS -static" \
    "${source_dir}"/configure \
        TOOLCHAIN_FOR_TARGET=llvm \
        --prefix="${prefix}" \
        --enable-all
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

        strip_command=strip \
    post_package_strip
}
