#! /bin/sh

name=wayland
from_source=wayland
imagedeps="build-essential pkg-config libffi-dev libexpat-dev libxml2-dev"
hostdeps="gcc pkg-config"

configure() {
    meson setup "${source_dir}" \
        --prefix=${prefix} \
        -Ddocumentation=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
