[package]
name = "busybox"
version = "1.37"
archs = ["x86_64"]

[[sources]]
url = "https://busybox.net/downloads/busybox-1.37.0.tar.bz2"
path = "busybox-1.37.0.tar.bz2"
patches = ["menix.patch"]

[dependencies]
build = ["base"]

[configure]
script = """
cp "${PACKAGE_DIR}/.config" "${BUILD_DIR}/.config.in"
envsubst < "${BUILD_DIR}/.config.in" > "${BUILD_DIR}/.config"
make KBUILD_SRC="${SOURCE_DIR}" -f "${SOURCE_DIR}/Makefile" oldconfig
"""

[build]
script = """
make -j${THREADS}
"""

[install]
script = """
make install
"""
