[package]
name = "host-gcc-freestanding"
version = "latest"
archs = ["x86_64"]
host = true
shared_source = "host-gcc"

[dependencies]
host = ["automake", "autoconf", "gcc", "ld", "as", "pkg-config"]
build = ["host-binutils", "mlibc-headers"]

[configure]
script = """
${SOURCE_DIR}/configure \
	--target=${OS_TRIPLET} \
	--enable-languages=c,c++,lto \
	--with-sysroot="${SYSROOT_DIR}" \
	--prefix="${PREFIX_HOST}" \
	--enable-threads=posix \
	--disable-multilib \
	--enable-initfini-array \
	--disable-shared \
	--disable-nls
"""

[build]
script = """
make -j${THREADS} inhibit_libc=true all-gcc
make -j${THREADS} inhibit_libc=true all-target-libgcc
"""

[install]
script = """
make install-gcc
make install-target-libgcc
"""
